module.exports = [
  { districtId: 'Honolulu-01', member: 'Kymberly Marcos Pine', email: 'kmpine@honolulu.gov', phone: '808-768-5001', county: 'Honolulu' },
  { districtId: 'Honolulu-02', member: 'Ernest Y. Martin', email: 'emartin@honolulu.gov', phone: '808-768-5002', county: 'Honolulu' },
  { districtId: 'Honolulu-03', member: 'Ikaika Anderson', email: 'ianderson@honolulu.gov', phone: '808-768-5003', county: 'Honolulu' },
  { districtId: 'Honolulu-04', member: 'Trevor Ozawa', email: 'tozawa@honolulu.gov', phone: '808-768-5004', county: 'Honolulu' },
  { districtId: 'Honolulu-05', member: 'Ann Kobayashi', email: 'akobayashi@honolulu.gov', phone: '808-768-5005', county: 'Honolulu' },
  { districtId: 'Honolulu-06', member: 'Carol Fukunaga', email: 'cafukunaga@honolulu.gov', phone: '808-768-5006', county: 'Honolulu' },
  { districtId: 'Honolulu-07', member: 'Joey Manahan', email: 'jmanahan@honolulu.gov', phone: '808-768-5007', county: 'Honolulu' },
  { districtId: 'Honolulu-08', member: 'Brandon Elefante', email: 'belefante@honolulu.gov', phone: '808-768-5008', county: 'Honolulu' },
  { districtId: 'Honolulu-09', member: 'Ron Menor', email: 'rmenor@honolulu.gov', phone: '808-768-5009', county: 'Honolulu' },
  { districtId: 'Maui-01', member: 'Mike White', email: 'mike.white@mauicounty.us', phone: '808-270-5507', county: 'Maui' },
  { districtId: 'Maui-02', member: 'Don Guzman', email: 'don.guzman@mauicounty.us', phone: '808-270-5501', county: 'Maui' },
  { districtId: 'Maui-03', member: 'Michael P. Victorino', email: 'michael.victorino@mauicounty.us', phone: '808-270-7760', county: 'Maui' },
  { districtId: 'Maui-04', member: 'Gladys C. Baisa', email: 'gladys.baisa@mauicounty.us', phone: '808-270-7939', county: 'Maui' },
  { districtId: 'Maui-05', member: 'Robert Carroll', email: 'robert.carroll@mauicounty.us', phone: '808-270-7246', county: 'Maui' },
  { districtId: 'Maui-06', member: 'Elle Cochran', email: 'elle.cochran@mauicounty.us', phone: '808-270-5504', county: 'Maui' },
  { districtId: 'Maui-07', member: 'Don Couch', email: 'don.couch@mauicounty.us', phone: '808-270-7108', county: 'Maui' },
  { districtId: 'Maui-08', member: 'Stacy Crivello', email: 'stacy.crivello@mauicounty.us', phone: '808-270-7678', county: 'Maui' },
  { districtId: 'Maui-09', member: 'G. Riki Hokama', email: 'riki.hokama@mauicounty.us', phone: '808-270-7768', county: 'Maui' },
  { districtId: 'Hawai\'i-01', member: 'Valerie T. Poindexter', email: 'valerie.poindexter@hawaiicounty.gov', phone: '808-961-8018', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-02', member: 'Aaron Chung', email: 'aaron.chung@hawaiicounty.gov', phone: '808-961-8272', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-03', member: 'Dennis “Fresh” Onishi', email: 'dennis.onishi@hawaiicounty.gov', phone: '808-961-8396', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-04', member: 'Greggor Ilagan', email: 'greggor.ilagan@hawaiicounty.gov', phone: '808-965-2712', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-05', member: 'Daniel K. Paleka, Jr.', email: 'daniel.paleka@hawaiicounty.gov', phone: '808-961-8026', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-06', member: 'Maile David', email: 'maile.david@hawaiicounty.gov', phone: '808-323-4277', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-07', member: 'Dru Mamo Kanuha', email: 'dru.kanuha@hawaiicounty.gov', phone: '808-323-4267', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-08', member: 'Karen Eoff', email: 'karen.eoff@hawaiicounty.gov', phone: '808-323-4280', county: 'Hawai\'i' },
  { districtId: 'Hawai\'i-09', member: 'Margaret Wille', email: 'margaret.wille@hawaiicounty.gov', phone: '808-887-2069', county: 'Hawai\'i' },
  { districtId: 'Kaua\'i-01', member: 'Mel Rapozo', email: 'mfrapozo@kauai.gov', phone: '808-241-4095', county: 'Kaua\'i' }
];
